[package]
name = "serde_test"
version = "0.1.0"
authors = ["ade-sede <adrien.de.sede@gmail.com>"]

[[bin]]
name = "server"
src = "src/bin/server" 

[[bin]]
name = "client"
src = "src/bin/client" 

[dependencies]
serde_derive = "1.0"
serde = "1.0.27"
serde_json = "1.0.9"
